spring.application.name=pokeshop
spring.datasource.url=jdbc:postgresql://localhost:5432/pokeshop
spring.datasource.username=postgres
spring.datasource.password=1Sh44n@))%9981
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true